/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package braileprueba1;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;

import javax.swing.JOptionPane;

/**
 *
 * @author WARY
 */
public class VentanaBraile extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBraile
     */
    public VentanaBraile() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void open(String docu){
        try{
            File objetofile = new File(docu);
            Desktop.getDesktop().open(objetofile);
            
        }
        catch (IOException ss){
            System.out.println(ss);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCajaT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 310));
        getContentPane().setLayout(null);

        txtCajaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCajaTActionPerformed(evt);
            }
        });
        getContentPane().add(txtCajaT);
        txtCajaT.setBounds(35, 124, 339, 30);

        jButton1.setFont(new java.awt.Font("Vijaya", 1, 14)); // NOI18N
        jButton1.setText("TRADUCIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 180, 120, 50);

        jLabel1.setFont(new java.awt.Font("Plantagenet Cherokee", 0, 14)); // NOI18N
        jLabel1.setText("NOTA: La traducción se  visualizara  en un archivo PDF");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 260, 360, 20);

        jLabel4.setFont(new java.awt.Font("Stencil", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("TRADUCTOR BRAILE ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 40, 250, 30);

        jLabel5.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 14)); // NOI18N
        jLabel5.setText("Introducir texto:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(35, 89, 130, 19);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/braileprueba1/316800.jpg"))); // NOI18N
        jLabel3.setText("lslsl");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 410, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCajaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCajaTActionPerformed
        
    }//GEN-LAST:event_txtCajaTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtCajaT.getText().compareTo("") !=0){
            IBrailee vari = new braileCodigo(txtCajaT.getText());
            vari.imprimirPdf();
            open("syui.pdf");
            txtCajaT.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null, "Ingrese el texto");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBraile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBraile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBraile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBraile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBraile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCajaT;
    // End of variables declaration//GEN-END:variables
}
